#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x10F2FD0D67DE9C2A (_@habnab.it)
#
Name     : vcversioner
Version  : 2.16.0.0
Release  : 1
URL      : https://pypi.python.org/packages/c5/cc/33162c0a7b28a4d8c83da07bc2b12cee58c120b4a9e8bba31c41c8d35a16/vcversioner-2.16.0.0.tar.gz
Source0  : https://pypi.python.org/packages/c5/cc/33162c0a7b28a4d8c83da07bc2b12cee58c120b4a9e8bba31c41c8d35a16/vcversioner-2.16.0.0.tar.gz
Source99 : https://pypi.python.org/packages/c5/cc/33162c0a7b28a4d8c83da07bc2b12cee58c120b4a9e8bba31c41c8d35a16/vcversioner-2.16.0.0.tar.gz.asc
Summary  : Use version control tags to discover version numbers
Group    : Development/Tools
License  : ISC
Requires: vcversioner-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
.. image:: https://travis-ci.org/habnabit/vcversioner.png
===========
vcversioner
===========

%package python
Summary: python components for the vcversioner package.
Group: Default

%description python
python components for the vcversioner package.


%prep
%setup -q -n vcversioner-2.16.0.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487856890
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1487856890
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
